timezone.settings:
  type: config_object
  label: 'Timezone settings'
  mapping:
    country:
      type: string
      label: 'Country.'
    city:
      type: string
      label: 'City.'
    timezone:
      type: string
      label: 'Timezone.'
